# 注释版本
server:
  port: 18085 # 端口号
spring:
  application:
    name: supreme-config # 应用名
  cloud:
    config:
      server:
        git:
          # 配置gitee的仓库地址
#          uri: https://gitee.com/StevenBlake/conf.git
          uri: https://gitee.com/su358524209/config.git
  # rabbitmq的配置信息；如下配置的rabbit都是默认值，其实可以完全不配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# 暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        # 暴露触发消息总线的地址
        include: bus-refresh
# Eureka服务中心配置
eureka:
  client:
    service-url:
      # 注册Eureka Server集群
      defaultZone: http://127.0.0.1:7001/eureka
# com.itheima 包下的日志级别都为Debug
logging:
  level:
    com: debug